package com.yandex.mobile.realty.testing.reporter;

import org.gradle.reporting.ReportRenderer;
import org.gradle.util.GradleVersion;

import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;

public abstract class TabbedPageRenderer<T> extends ReportRenderer<T, SimpleHtmlWriter> {
    private T model;

    protected T getModel() {
        return model;
    }

    protected abstract String getTitle();

    protected abstract ReportRenderer<T, SimpleHtmlWriter> getHeaderRenderer();

    protected abstract ReportRenderer<T, SimpleHtmlWriter> getContentRenderer();

    protected String getPageTitle() {
        return getTitle();
    }

    @Override
    public void render(final T model, SimpleHtmlWriter htmlWriter) throws
        IOException {
        this.model = model;
        htmlWriter.startElement("head")
            .startElement("meta").attribute("http-equiv", "Content-Type").attribute("content", "text/html; charset=utf-8").endElement()
            .startElement("title").characters(getPageTitle()).endElement()
            .startElement("link").attribute("href", "css/base-style.css").attribute("rel", "stylesheet").attribute("type", "text/css").endElement()
            .startElement("link").attribute("href", "css/style.css").attribute("rel", "stylesheet").attribute("type", "text/css").endElement()
            .startElement("script").attribute("src", "js/report.js").attribute("type", "text/javascript").characters("").endElement() //html does not like <a name="..."/>
            .endElement();

        htmlWriter.startElement("body")
            .startElement("div").attribute("id", "content")
            .startElement("h1").characters(getTitle()).endElement();
        getHeaderRenderer().render(model, htmlWriter);
        getContentRenderer().render(model, htmlWriter);
        htmlWriter.startElement("div").attribute("id", "footer")
            .startElement("p").characters("Generated by ")
            .startElement("a").attribute("href", "http://www.gradle.org").characters(String.format("Gradle %s", GradleVersion.current().getVersion())).endElement()
            .characters(String.format(" at %s", DateFormat.getDateTimeInstance().format(new Date())))
            .endElement()
            .endElement()
            .endElement();
    }
}